### ISSUE TITLE
key could be "tail" in this loop. is this intended?

### ISSUE THREAD

**Issue by IntendedConsequence** [renatomaia/coutil#1]
Hi, I was reading your implementation of events and promises, looking for ideas, when I noticed this loop doesn't have condition distinguishing threads from the key "tail" which also resides in the table. In which case previous is going to have the value of string "tail". Is this intended?
https://github.com/renatomaia/coutil/blob/122d11a25796af08e7b0c659f286ca6f9a6f3369/lua/coutil/event.lua#L48-L53

**Comment by renatomaia** [comment]
No, it was not intended. Thanks a lot for spotting this. It is a serious bug (which I believe already happened in some of my projects using this library). It would be very hard to debug this.
